### ISSUE TITLE
Can't scroll in treeview

### ISSUE THREAD

**Issue by pwr22** [olmokramer/atom-autohide-tree-view#77]
Without this addon I can scroll down in the tree view as needed. WIth this addon, scrolling no longer works

This was with the latest version, so **v0.25.1** I assume

**Comment by exdeniz** [comment]
Scroll work on "Push" only, please fix it

**Comment by chl1996** [comment]
+1

**Comment by elcarim5efil** [comment]
you might just add some code in the style file.

``` css
.tree-view-resizer {
  ...
  height: 100% !important;
  ...
}
This should fix the problem temporarily.
```
