### ISSUE TITLE
Auto-hide isn't working for me...

### ISSUE THREAD

**Issue by yaniv11386** [olmokramer/atom-autohide-tree-view#92]
ver. 0.25.1
OS Windows 10 (64)

After installation, auto hide isn't working and when I manually close the tree, it doesn't open as well.

**Comment by TomLavenziano** [comment]
Auto-hide has been broken since Atom v1.17.0 when Atom switched to the new tool panes

**Comment by ghost** [comment]
Ok, so is there any way of fixing this bug, or is there an alternative package that fills this function?

**Comment by sanarena** [comment]
I've created this simple package to be able do my daily tasks without file tree annoyance for now, far from original plugin but it just works: https://atom.io/packages/filetree-autohide

**Comment by ghost** [comment]
Works well, many thanks!

**Comment by B-lvlax** [comment]
Thanks to @sanarena - it is great idea!! I tried many others solution so i forgot about css. Another way to fix the problem is to add styles directly to Atom stylesheet. For example to show tree view if your window is great than 800px:
``` Css
@media screen and (min-width: 800px) {
  .atom-dock-inner.left.atom-dock-open {
    width: unset;
  }
  .atom-dock-inner.left.atom-dock-open:hover {
    width: initial;
  }
}
```
